FROM mcr.microsoft.com/playwright:v1.50.1-noble AS rustbuilder

WORKDIR /app

# Get Ubuntu packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cargo

COPY ../headless_browser/ ./headless_browser
COPY ../headless_browser_lib/ ./headless_browser_lib
COPY ../benches/ ./benches
COPY ../Cargo.* .

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env && rustup update stable
RUN RUST_LOG=error cargo install --no-default-features --path headless_browser

FROM mcr.microsoft.com/playwright:v1.50.1-noble

ARG VERSION=latest

COPY ../scripts/build-unpatched.sh .
COPY ../local.conf /etc/fonts/local.conf

RUN apt-get update && apt-get install -y \
    build-essential \
    tini curl

RUN ./build-unpatched.sh

# Add Chrome as a user
RUN mkdir -p /usr/src/app \
    && useradd -m chrome \
    && chown -R chrome:chrome /usr/src/app

EXPOSE 9222 6000 9223

USER root

COPY --from=rustbuilder /root/.cargo/bin/headless_browser /usr/local/bin/headless_browser
COPY ../scripts/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

ENV REMOTE_ADDRESS=0.0.0.0
ENV LAUNCH=init
ENV DEFAULT_PORT=9223
ENV DEFAULT_PORT_SERVER=6000
ENV DEFAULT_LAUNCH_NAME=/out/latest/headless-shell/headless-shell

ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
